# Don't print a new line at the start of the prompt
add_newline = false

# Show current directory
[directory]
truncation_length = 8
truncation_symbol = ".../"
format = "[$path]($bold cyan) | "

# Show the conda prompt
[conda]
symbol = "ğŸ "
ignore_base = false
disabled = false
format = "[$symbol$environment](dimmed green) "

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = "on [$symbol$branch]($style) | "
